### ISSUE TITLE
New option - Search music in YT.

### ISSUE THREAD

**Issue by FlamesX-128** [paij0se/ymp3cli#8]
# New option - Search music in YT.
## English
The idea is to add a new option to search for videos on YT. The results should return the title, the link and optionally the image.

With the link you only copy and paste it in the option to download music on YT and/or add based on the results, allow the index to be entered and it will download the video.

## Español
La idea consiste que se agregue una nueva opcion para buscar videos en YT. Los resultados deberan retornar el titulo, el link y opcionalmente la imagen.

Con el link solo lo copias y pegas en la opcion para descargar musica en YT y/o agregar basandose de los resultados, permitir introducir el indice y que este descargue el video.

**Comment by paij0se** [comment]
`-sp` flag allows you search songs from youtube using spotdl

<img src="https://media.discordapp.net/attachments/809819016357085204/954536487943295077/unknown.png">
